esphome:
  name: gme-xrs-mux
  friendly_name: GME XRS MUX

esp32:
  board: lolin_s3_pro
  framework:
    type: esp-idf

logger:
  level: DEBUG

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:

esp32_ble_tracker:

ble_client:
  - mac_address: <YOUR MAC ADDRESS HERE>
    id: gme_xrs_ble_client
    auto_connect: true

external_components:
  - source: git://github/andrewbackway/esphome-gme_xrs_radio

gme_xrs_radio:
  - id: gme_xrs_radio1
    ble_client_id: gme_xrs_ble_client


